### ISSUE TITLE
Switchboard recipe triggers CUDA OOM exception

### ISSUE THREAD

**Issue by JinZr** [lhotse-speech/lhotse#1097]
Manifests produced by the default `lhotse prepare switchboard` recipe will trigger CUDA OOM due to very long uncut utterances.

An AssertionError will be further triggered when `trim_to_supervisions(keep_all_channels=True)` applied to CutSet: `AssertionError: Supervisions starting before the cut are not supported for ASR (sup id: sw4349A-ms98-a-0002, cut id: 4ed12f02-29d9-7813-afe6-0ffd889da819)`.

```python
train_cuts = switchboard.train_all_cuts().subset(last=2388).trim_to_supervisions(keep_all_channels=True)

def remove_short_and_long_utt(c: Cut):
       # Keep only utterances with duration between 1 second and 600 seconds
       #
       # Caution: There is a reason to select 600.0 here. Please see
       # ../local/display_manifest_statistics.py
       #
       # You should use ../local/display_manifest_statistics.py to get
       # an utterance duration distribution for your dataset to select
       # the threshold
       return 1.0 <= c.duration <= 600.0

train_cuts = train_cuts.filter(remove_short_and_long_utt)
train_dl = switchboard.train_dataloaders(train_cuts)

valid_cuts = switchboard.train_all_cuts().subset(first=50).trim_to_supervisions(keep_all_channels=True)
valid_dl = switchboard.valid_dataloaders(valid_cuts)
```

**Comment by desh2608** [comment]
I don't think the icefall ASR recipes support MultiCuts at the moment, so you should use "keep_all_channels=False".

**Comment by JinZr** [comment]
Dear Desh,

When set `keep_all_channels=False`, another assertion was triggered:

`AssertionError: Trimmed cut has supervisions with different channels.
Either set `ignore_channel=True` to keep original channels or
`keep_overlapping=False` to retain only 1 supervision per trimmed cut.`

if set `keep_overlapping` to `False`, then there is no guarantee that all
cuts have features:

`assert all(cut.has_features for cut in cuts)
AssertionError`.

Best regards

**Comment by desh2608** [comment]
Are you using an existing recipe? Also, please make sure you have the latest Lhotse.

**Comment by JinZr** [comment]
Dear Desh,

Yes, I'm using the latest lhotse.

I'm trying to make a recipe for swbd using icefall, a lot of the training
code is from the librispeech recipe, that's why i thought most of the
things should work in the same way as on the librispeech dataset.

Best regards

**Comment by danpovey** [comment]
Maybe switchboard recipe needs to be re-tested to check for regressions?
We don't have switchboard in Beijing so can't help with that.

**Comment by pzelasko** [comment]
It's hard to say what exactly went wrong without seeing your code for preparing cuts, but in principle the following should work:

```python
# step 1: get a raw cutset
swbd = prepare_switchboard("path/to/swbd")
cuts = CutSet.from_manifests(**swbd)

# step 2: segment it to utterances
cuts = cuts.trim_to_supervisions(keep_overlapping=False)

# step 3: extract features
cuts = cuts.compute_and_store_features(...)

# step 4: save to disk
cuts.to_file(...)
```

If the above workflow doesn't work, Dan had a good point about regression testing SWBD -- I also currently have no access though.

**Comment by JinZr** [comment]
I think this issue might be related to MultiCuts, this is the manifest I generated for [eval2000](https://drive.google.com/file/d/1D2ccLmiERE__Ji4Sfqe2US4PuhNa_VfY/view?usp=sharing), but there's no way to apply trim_to_supervisions to it, without trimming an audio file can be excessive long to be loaded into GPUs.

Another thing I'm not sure about is that the swbd and eval2000 has some very short utterances (duration less than 0.5) that can hardly be used for feature extraction and training, for example:

Eval2000 Cut statistics:
```
╒═══════════════════════════╤══════════╕
│ Cuts count:               │ 2709     │
├───────────────────────────┼──────────┤
│ Total duration (hh:mm:ss) │ 01:39:19 │
├───────────────────────────┼──────────┤
│ mean                      │ 2.2      │
├───────────────────────────┼──────────┤
│ std                       │ 1.8      │
├───────────────────────────┼──────────┤
│ min                       │ 0.1      │
├───────────────────────────┼──────────┤
│ 25%                       │ 0.7      │
├───────────────────────────┼──────────┤
│ 50%                       │ 1.7      │
├───────────────────────────┼──────────┤
│ 75%                       │ 3.1      │
├───────────────────────────┼──────────┤
│ 99%                       │ 8.0      │
├───────────────────────────┼──────────┤
│ 99.5%                     │ 8.3      │
├───────────────────────────┼──────────┤
│ 99.9%                     │ 11.3     │
├───────────────────────────┼──────────┤
│ max                       │ 14.1     │
├───────────────────────────┼──────────┤
│ Recordings available:     │ 2709     │
├───────────────────────────┼──────────┤
│ Features available:       │ 0        │
├───────────────────────────┼──────────┤
│ Supervisions available:   │ 2709     │
╘═══════════════════════════╧══════════╛
Speech duration statistics:

╒══════════════════════════════╤══════════╤══════════════════════╕
│ Total speech duration        │ 01:39:19 │ 100.00% of recording │
├──────────────────────────────┼──────────┼──────────────────────┤
│ Total speaking time duration │ 01:39:19 │ 100.00% of recording │
├──────────────────────────────┼──────────┼──────────────────────┤
│ Total silence duration       │ 00:00:00 │ 0.00% of recording   │
╘══════════════════════════════╧══════════╧══════════════════════╛
```
I'm wondering whether this has something to do with failed checking at: 
```
File "/star-home/jinzengrui/lib/miniconda3/envs/dev39/lib/python3.9/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.9.egg/lhotse/dataset/collation.py", line 129, in collate_features                                                                                                                                                                                             assert all(cut.has_features for cut in cuts)                                                                                                                                            AssertionError                                                                                                                                                                              
```

**Comment by desh2608** [comment]
Can you provide some more details such as:

Show a cut generated originally from the recording and supervisions.

Show a cut that's obtained after applying trim to supervisions with the options keep_overlapping=False and keep_all_channels=False.

**Comment by JinZr** [comment]
Dear Desh,

Please check cut files in [here](https://drive.google.com/drive/folders/14XD3OCVJ9wSv06n_gCiHeuAIt8gKSaGE?usp=sharing). `eval2000_recordings_all.jsonl.gz` and `eval2000_supervisions_unnorm.jsonl.gz` are obtained using lhotse prepare eval2000, `eval2000_supervisions_all.jsonl.gz` is the supervision set after text norm.

The cutset `eval2000_cuts_all.jsonl.gz` in the provided link cannot be trimmed with 
```
lhotse cut trim-to-supervisions \
            --discard-overlapping \
            --discard-extra-channels \
            data/manifests/eval2000/eval2000_cuts_all.jsonl.gz \
            data/manifests/eval2000/eval2000_cuts_all_trimmed.jsonl.gz
```
as it throws this error:
```
File "/star-home/jinzengrui/lib/miniconda3/envs/dev39/lib/python3.9/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.9.egg/lhotse/cut/base.py", line 489, in trim_to_supervisions
AssertionError: Trimmed cut has supervisions with different channels. Either set `keep_all_channels=True` to keep original channels or `keep_overlapping=False` to retain only 1 supervision per trimmed cut.
```

**Comment by desh2608** [comment]
I tried the following sequence of commands and it works fine:
```
lhotse prepare eval2000 /export/common/data/corpora/LDC data/
lhotse cut simple -r data/eval2000_recordings_all.jsonl.gz -s data/eval2000_supervisions_unnorm.jsonl.gz data/eval2000_cuts.jsonl.gz
lhotse cut trim-to-supervisions --discard-overlapping --discard-extra-channels data/eval2000_cuts.jsonl.gz data/eval2000_cuts_trimmed.jsonl.gz
```

Perhaps there is an issue with the supervisions you created after normalization?

**Comment by desh2608** [comment]
I have reproduced the error locally. Trying to debug it now.

**Comment by desh2608** [comment]
This should resolve the issue: https://github.com/lhotse-speech/lhotse/pull/1126

**Comment by JinZr** [comment]
Thanks Desh! I'll look into it.

**Comment by JinZr** [comment]
This trimming issue has been fixed.
